source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jemoji'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'webrick', '~> 1.8'
gem 'connection_pool'
